name: Waka Charts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: AndrewDongminYoo/wakatime-svg@v1.4.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
